import React from 'react';
import { ViewStyle } from 'react-native';
import { colors } from '../../config/theme';
import {
  Package,
  Truck,
  MapPin,
  Navigation,
  Phone,
  MessageSquare,
  Star,
  User,
  Bell,
  Calendar,
  DollarSign,
  CheckCircle,
  XCircle,
  AlertCircle,
  Clock,
  Camera,
  Upload,
  ChevronRight,
  Menu,
  Settings,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Plus,
  Minus,
  X,
  Search,
  Filter,
  MoreHorizontal,
  Heart,
  Share,
  Download,
  Edit,
  Trash2,
  Save,
  RefreshCw,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Home,
  Map,
  CreditCard,
  Shield,
  HelpCircle,
  Info,
  ExternalLink,
  Copy,
  Check,
  AlertTriangle,
  Zap,
  Target,
  TrendingUp,
  BarChart3,
  PieChart,
  Activity,
  Users,
  TruckIcon,
  PackageIcon,
  MapIcon,
  NavigationIcon,
  PhoneIcon,
  MessageSquareIcon,
  StarIcon,
  UserIcon,
  BellIcon,
  CalendarIcon,
  DollarSignIcon,
  CheckCircleIcon,
  XCircleIcon,
  AlertCircleIcon,
  ClockIcon,
  CameraIcon,
  UploadIcon,
  ChevronRightIcon,
  MenuIcon,
  SettingsIcon,
  MailIcon,
  LockIcon,
  EyeIcon,
  EyeOffIcon,
  PlusIcon,
  MinusIcon,
  XIcon,
  SearchIcon,
  FilterIcon,
  MoreHorizontalIcon,
  HeartIcon,
  ShareIcon,
  DownloadIcon,
  EditIcon,
  Trash2Icon,
  SaveIcon,
  RefreshCwIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  HomeIcon,
  MapIcon as MapIconComponent,
  CreditCardIcon,
  ShieldIcon,
  HelpCircleIcon,
  InfoIcon,
  ExternalLinkIcon,
  CopyIcon,
  CheckIcon,
  AlertTriangleIcon,
  ZapIcon,
  TargetIcon,
  TrendingUpIcon,
  BarChart3Icon,
  PieChartIcon,
  ActivityIcon,
  UsersIcon,
} from 'lucide-react-native';

const icons = {
  package: Package,
  truck: Truck,
  mapPin: MapPin,
  navigation: Navigation,
  phone: Phone,
  messageSquare: MessageSquare,
  star: Star,
  user: User,
  bell: Bell,
  calendar: Calendar,
  dollarSign: DollarSign,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  clock: Clock,
  camera: Camera,
  upload: Upload,
  chevronRight: ChevronRight,
  menu: Menu,
  settings: Settings,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  plus: Plus,
  minus: Minus,
  x: X,
  search: Search,
  filter: Filter,
  moreHorizontal: MoreHorizontal,
  heart: Heart,
  share: Share,
  download: Download,
  edit: Edit,
  trash2: Trash2,
  save: Save,
  refreshCw: RefreshCw,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  home: Home,
  map: Map,
  creditCard: CreditCard,
  shield: Shield,
  helpCircle: HelpCircle,
  info: Info,
  externalLink: ExternalLink,
  copy: Copy,
  check: Check,
  alertTriangle: AlertTriangle,
  zap: Zap,
  target: Target,
  trendingUp: TrendingUp,
  barChart3: BarChart3,
  pieChart: PieChart,
  activity: Activity,
  users: Users,
};

export type IconName = keyof typeof icons;

interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  style?: ViewStyle;
}

export const Icon: React.FC<IconProps> = ({
  name,
  size = 24,
  color = colors.primary,
  style,
}) => {
  const IconComponent = icons[name];
  
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }

  return <IconComponent size={size} color={color} style={style} />;
};